### ISSUE TITLE
CSS Editor not saving

### ISSUE THREAD

**Issue by neilcreagh** [omeka/classic-enduser#11]
We've just upgraded a site to Silver Plan and I've been trying to add custom CSS but when I click save changes it doesn't seem to save them. Saving goes back to the Plug-in list page with the message "The CSS Editor plugin was successfully configured!" but when I go back into it again there is nothing saved in that textarea. 

The site is http://travellercollection.omeka.net

**Comment by mebrett** [comment]
Questions and errors regarding Omeka.net should be submitted via the [Contact form](https://omeka.org/contact/) as answers will depend on your plan. Thank you.
