### ISSUE TITLE
2 broken links in Omeka Classic User Manual

### ISSUE THREAD

**Issue by adehner** [omeka/classic-enduser#18]
On this page:
https://omeka.org/classic/docs/

In this block of text:
<img width="718" alt="screen shot 2018-06-19 at 10 54 05 am" src="https://user-images.githubusercontent.com/6174191/41615193-6fe1644c-73af-11e8-9f09-c4f1a9d093dc.png">

The "appearance" and "site settings" links are broken. 

Thought you guys would like to know. Thanks for all of your work!!

**Comment by mebrett** [comment]
Thank you for the heads up!
