### ISSUE TITLE
Geolocation: List global mapbox classic map IDs

### ISSUE THREAD

**Issue by zerocrates** [omeka/classic-enduser#22]
We link to the Mapbox docs which _used_ to show this list, but they seem to have removed it from their docs, so maybe we should just list it ourselves:

mapbox.streets
mapbox.light
mapbox.dark
mapbox.satellite
mapbox.streets-satellite
mapbox.wheatpaste
mapbox.streets-basic
mapbox.comic
mapbox.outdoors
mapbox.run-bike-hike
mapbox.pencil
mapbox.pirates
mapbox.emerald
mapbox.high-contrast

**Comment by zerocrates** [comment]
Update to this: Mapbox is just deprecating/removing the API that these styles go with, so I guess there's no need for us to list them.

But: because they're updating it there's a forthcoming Geolocation (3.2) that uses a _different_ API from them with a different set of names.

Plus side: their docs do contain a list of the valid global styles for this new system: https://docs.mapbox.com/api/maps/#mapbox-styles (minus the `mapbox://styles/` part for each)

Minus side: the upgrade can handle the style names that align between these two but not any others; there doesn't appear to be any equivalent for most of the "odder" ones in that old list like emerald and wheatpaste; users using their own styles would have to update those references also.

So we'll need to update the link here and have some brief mention of version 3.2 and upgrading.

**Comment by mebrett** [comment]
Would these updates be concurrent with any tweaks to the docs to reflect changes for 3.2?
And would be you willing to draft a sentence for that?

**Comment by zerocrates** [comment]
So, 3.2 has a couple other things but I don't think they're doc-relevant: it fixes an issue where you could put a pin on the map outside the normal bounds of the world (like if you zoom way out you could pin on the Earth that's several copies over to the left or right), and fixes a bug where re-placing the marker on a form several times would cause multiple markers to appear.

As for the sentence: we have now

> Either enter the ID for your own map (see the MapBox documentation) or one of the generally available map ids

instead/additionally:

> The "map ID" that goes here is the part of a Mapbox "Style URL" that comes after "mapbox://styles/". You can use your own maps or one of the [globally available styles](https://docs.mapbox.com/api/maps/#mapbox-styles). Leaving this input blank will use the default street map. 
>
> As of June 1, 2020, Mapbox has deprecated older-style maps. Geolocation 3.2 and up support the newer Mapbox API, and the plugin will automatically update your selected Map ID if you were using one of the "standard" map types. If you had specified a custom map ID, you may need to update it after upgrading Geolocation.

**Comment by zerocrates** [comment]
That text seem fine to you?

**Comment by mebrett** [comment]
That works for me.
