### ISSUE TITLE
Case studies links issues

### ISSUE THREAD

**Issue by zerocrates** [omeka/classic-enduser#26]
It just kind of looks like the case studies pages, or at least some of them, got kind of left by the wayside: they include old codex links and stuff like that.

**Comment by zerocrates** [comment]
It's the case_studies folder and the GettingStarted/Project_Planning_Case_Studies.md (which doesn't seem to be linked in the navigation anywhere, could be obsolete?)

**Comment by mebrett** [comment]
`GettingStarted/Project_Planning_Case_Studies` is old - we can remove the page from the current versions of the site.

**Comment by zerocrates** [comment]
presumably that includes the case_studies folder too, then
