### ISSUE TITLE
Clear out unused pages

### ISSUE THREAD

**Issue by mebrett** [omeka/classic-enduser#29]
List of docs not referenced in the navigation generated by MkDocs

**Comment by zerocrates** [comment]
- Content/About_Item_Types.md
  - GettingStarted/Classic_vs_Net.md
  - GettingStarted/How_Might_You_Use_Omeka.md
  - GettingStarted/Project_Planning.md
  - GettingStarted/Teach_with_Omeka.md
  - Plugins/ExhibitBuilder_v2.md
  - Technical/Contributed_API_clients.md
  - Technical/Setting_PHP_Path.md

**Comment by mebrett** [comment]
Not sure what to do about the "Classic vs. Net" page - it's useful information, but we do get in to some of it over in the FAQ on the forum.

**Comment by zerocrates** [comment]
We never did do anything about the "Classic vs. Net" page, it's still in there as an orphan.
