### ISSUE TITLE
Check over installation instructions

### ISSUE THREAD

**Issue by zerocrates** [omeka/classic-enduser#3]
This is one of the most important parts of the manual and seems to have lost a few things in translation.

There's quite a few broken links (a known issue, I think), but also some links to things that don't appear to be their own pages anymore, like Preparing to Install. There's also remaining references to distribution-specific instructions for Fedora, Ubuntu, etc., and I don't think those actually made it over into the new manual (with good cause, but then we should remove the references to them as well).

**Comment by mebrett** [comment]
Should be [resolved](https://github.com/omeka/classic-enduser/blob/mbrett-test/docs/Installation/Installation.md) now.
