### ISSUE TITLE
Upgrade Guide from 2 to 3

### ISSUE THREAD

**Issue by smilebasti** [omeka/classic-enduser#41]
Hi, 
nice to see an update for Omeka Classic.

I can't seem to find an upgrade guide from version 2 to 3. Only 1 to 2.
I am currently running 2.7.1.

Would be nice to have that in the Docs.

Thanks ahead

**Comment by sharonmleon** [comment]
Those (https://omeka.org/classic/docs/Installation/Upgrading/) actually are the upgrade instructions from 2.0 to 3.0, with special notes for the things that are different for the early 1.0 versions.
