### ISSUE TITLE
Miscellaneous issues

### ISSUE THREAD

**Issue by zerocrates** [omeka/classic-enduser#6]
- Content / Items
    - Edit an item section looks to be halfway through a rewrite
    - Batch Edit.png screenshot doesn't exist

- Admin / Plugin Shortcodes
    - Separating the plugin shortcodes from the others feels like a step backwards, plus now that big table has to be replicated

- Admin / Themes
    - Same screenshot used for "header and footer" and "homepage" options (homepage is the one that's missing)

- Admin / Search Settings
    - Image "Search settings page, with Item, File, and Collection checkboxes active" doesn't exist

- Plugins / Geolocation
    - Duplicate shortcode documentation

- Plugins / Shortcode Carousel
    - Duplicate shortcode documentation

- Troubleshooting / Troubleshooting
    - Fairly bad advice about checking for mod_rewrite (a holdover from the old docs, and the docs themselves even complain about it)

- General
    - No equivalent for "Report a Bug" page
    - Many (all?) shortcode pages maintain mediawiki definition list wikitext, resulting in colons and semicolons all over the place

**Comment by mebrett** [comment]
Re Troubleshooting - should I just delete the section on 404 errors, or is there now a better practice?

**Comment by mebrett** [comment]
All of these have been fixed with the exception of removing the section on 404 errors.
