### ISSUE TITLE
Update for the new captcha pull

### ISSUE THREAD

**Issue by patrickmj** [omeka/classic-enduser#7]
A recent PR adds Captcha v2 support, which we should document and update screenshots for alongside the next release.

**Comment by patrickmj** [comment]
The language change is still in play: https://github.com/omeka/Omeka/issues/803

**Comment by mebrett** [comment]
It too a little work to figure out where to find the public/site key, but once I got that, the new system works. We will have to remind people that if they want to use Captcha v2, they need to update the plugins using it. The old ReCaptcha documentation page just lists Simple Contact and Commenting - do any other plugins make use of the ReCaptcha?

**Comment by patrickmj** [comment]
Not 100% sure, but I suspect Contribution uses it, depending on the settings.

**Comment by zerocrates** [comment]
Commenting needs an update because it had some issues with its use of the captcha, the others shouldn't need to be updated (and Contribution definitely does use it).

**Comment by mebrett** [comment]
Documentation is written and will be ready to go once I can get a screencap of the reCAPTCHA settings section (if we change "public"/"private" to "site"/"secret"). Will the dropdown option for v1/v2 stay or are we removing that once v1 is turned off?
